name: Baltic Control Jordan
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
author: {}
color:
  lightness: 0.2541079780212855
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  saturation: 0.26165361312722174
  brandStrength: 0.45092072767459807
  rhythmicContrast: 0.5488883316397872
